### ISSUE TITLE
New folder button when move/copy does not work as intended

### ISSUE THREAD

**Issue by BaccanoMob** [gtsteffaniak/filebrowser#1001]
Clicking New folder after moving folders when move/copy, creates in the initial directory but not the directory I moved into.

Steps to reproduce:

- Select some files/folder
- Click move/copy
- Go to any different folder
- Choose `New Folder` and input some name
- The new folder is at the initial directory without moving/copying anything

Expected behaviour:
- New folder at the destination and have the selected items in it.

**Comment by Kurami32** [comment]
I was about to open an issue about this too xd. I recorded a video, so I'll post it here. 

https://github.com/user-attachments/assets/7a14b104-4f6f-487f-a88e-cec73c926cc9

**Comment by gtsteffaniak** [comment]
seems to be an intermittent issue caused by some async issue. I will address

**Comment by gtsteffaniak** [comment]
I believe this was fixed in 0.7.17, at least I remember fixing it :)

**Comment by BaccanoMob** [comment]
@gtsteffaniak I do not think this is fixed. Checked again now. (I cant reopen the issue btw)

Clicking `New Folder` creates folder in the source directory (and moves the user to the new folder). It does not create the folder in the directory  of the popup nor copy/move contents. 

It would be good to create the folder in the directory of the popup and refresh the popup (so the new folder is visible in the popup). Then we move to the folder and copy/move the content. (Will be useful if some users want to copy/move to `n` folder depth). Pretty much what you see in windows explorer.

**Comment by gtsteffaniak** [comment]
Is this still an issue?

**Comment by BaccanoMob** [comment]
@gtsteffaniak yes, happens with `0.8.2-beta` as well. (Checked again now)

**Comment by BaccanoMob** [comment]
@gtsteffaniak I didnt check the source code but context menu `New Folder` and copy/move popup's `New Folder` uses the same logic, that is, create a folder and move into it. Not sure which is issue it was, I remember you saying something that you did not want to auto navigate into anything. Maybe it should apply here as well.

- Context Menu/File actions > Creates a folder and does not navigate into it (like in windows explorer, or any desktop file browser I think) then updates grid/list
- Copy/Move popup > Creates a folder in the selected directory (not the initial directory) then updates the list in popup.

**Comment by Kurami32** [comment]
> * Creates a folder and does not navigate into it (like in windows explorer, or any desktop file browser I think) then updates grid/list

@gtsteffaniak I also want this, when you create a folder this auto-navigate to the new folder, like mkdir + cd commands. E.g: I want to create multiple folders on the current one, I need to navigate back every time I create a new folder.

**Comment by gtsteffaniak** [comment]
understood, thanks for the clarification!

**Comment by gtsteffaniak** [comment]
I believe this is resolved already -- file and folders are opened after creation.  I believe that's what was left on this, reopen if theres something else.

**Comment by BaccanoMob** [comment]
@gtsteffaniak sorry to say this but still not done... and I cant reopen it.

An example from my windows machine (when trying to open something)

https://github.com/user-attachments/assets/852c2474-ff1b-4721-b8ba-0c71ea4a0419

Notice that new folder gets created but the popup still stays in the directory (aka UI does not navigate).

And this is via filebrowser of me trying to move a txt file into a new subfolder inside test folder. 

https://github.com/user-attachments/assets/c0957fa7-98bf-49ae-8cb8-995b8534f5e5

New folder gets created in the source directory but not the destination  directory (or the directory I navigated to). Then moves to the new folder (a folder that was created at a wrong place). It forgets to move/copy the selection. 

What I expect is the new folder adds to list in the popup. Thats about it so I can then navigate into it or just create more folders (like in first clip). And finally move/copy the selection.

Most frustrating thing about this is when I explicitly select a few items in a long list.

**Comment by BaccanoMob** [comment]
@gtsteffaniak I updated the comment post in this issue on possible expected behaviors (though I prefer like in windows or any OS in that matter). The steps to reproduce are the still same (seen in the last clip).
