### ISSUE TITLE
Files in share links download and/or error instead of displaying in browser.

### ISSUE THREAD

**Issue by Darkassassin07** [gtsteffaniak/filebrowser#1089]
Running version 0.8.0-beta

I have a folder shared via a share link that only contains pdf files and folders with more pdf files.

When viewing that link and opening files with filenames that contain a '+', that '+' is stripped from the file path resulting in 'something really went wrong' and 'error fetching share from server' displayed to the client Aswell as a file not found error on the backend in docker logs.

When opening files that do not contain a '+', the file immediately downloads as an attachment instead of displaying the file in the browser. This leaves the browser viewing an empty page.

If I login instead of viewing via share link, these pdf files open and display in-browser just fine, as they have with previous versions.

**Comment by christaikobo** [comment]
You have actually described 2 different problems. 

For the second problem, I have created a separate issue: https://github.com/gtsteffaniak/filebrowser/issues/1090

**Comment by gtsteffaniak** [comment]
thanks ill track the first issue on here, will fix in 0.8.1!

**Comment by Darkassassin07** [comment]
@gtsteffaniak 

Pulled the latest (0.8.1) and this is still occurring.

{"status":500,"message":"error processing filelist: /Parts Lists/Graco - Texture Sprayer Manual Parts - RTX1400si.pdf"}

The filename actually contains a '+' between 'Manual' and 'Parts', but it's replaced with a space only while viewing via share link.

It opens correctly when actually logged in instead of via share link.

**Comment by gtsteffaniak** [comment]
Ah thats a message from the raw download endpoint.I just tried with my example and I can see it in the share UI, but also get that error in the download.

I'll probably fix this with another bugfix release sunday.

**Comment by Darkassassin07** [comment]
I should note; I'm not asking it to download files, it's still just downloading instead of opening it in the viewer.

**Comment by christaikobo** [comment]
Yes you are right, like I said I created a separate issue for this: https://github.com/gtsteffaniak/filebrowser/issues/1090

And yes it is not fixed.

**Comment by gtsteffaniak** [comment]
will follow up on #1090

**Comment by gtsteffaniak** [comment]
should all be solved in 0.8.2

**Comment by Darkassassin07** [comment]
@gtsteffaniak 
Pulled 0.8.2-beta

Pdf files containing a '+' in the filename now open the pdf viewer instead of directly trying to download, but they still do not display any contents:

<img width="1920" height="932" alt="Image" src="https://github.com/user-attachments/assets/90e1af5e-6866-4982-bc15-53d946215272" />

Selecting 'download' from the three dots in the top right, results in the same 500 status as previously commented. The '+' is still stripped and replaced with a space resulting in file not found.

**Comment by gtsteffaniak** [comment]
can you test 0.8.5?

**Comment by Darkassassin07** [comment]
Woohoo!

Pulled the latest, re-renamed some pdf files to include '+' again, and they seem to work as expected.

They can be opened in the in-browser viewer, or successfully downloaded without error.

Thanks! :)
