### ISSUE TITLE
Unable to sort numerically

### ISSUE THREAD

**Issue by TannerDeLucia** [gtsteffaniak/filebrowser#230]
**Description**
There is alphabetical sorting by name within folders but there is no numerical sorting by name. 

**Expected behaviour**
When sorting by name, my files would appear as 1,2,3,4,5,6,etc.

**What is happening instead?**
My files appear as 1,10,100,1000,1001,1002,etc.

**Additional context**
Some of these folders contain multiple thousands of picture files named 1-3000 so numerical sorting is needed. 

**How to reproduce?**
Name files 1-1000 and sort by name. 

**Files**
No relevant files.

**Comment by gtsteffaniak** [comment]
Understand.. Will add sorting more sorting functionality on next release.

**Comment by TannerDeLucia** [comment]
Upgrading to v0.3.1 did not resolve the issue. I recorded the behavior that happens in your fork and the behavior that happens in the original. Please let me know if you need any additional information. 

Your fork:
https://gyazo.com/b68879db1d3d6392178a35c282a97665

Default original filebrowser behavior:
https://gyazo.com/280253899e0fad0d202406a9e0634ab1

**Comment by gtsteffaniak** [comment]
Hmmm,  thanks for showing what you were describing.

The issue I fixed was on the backend, that looks like an issue with the frontend behavior. I am getting v0.3.2 ready for tomorrow, ill do the same process on the frontend to make sure it sorts correctly.

**Comment by gtsteffaniak** [comment]
v0.3.2 will come out tomorrow:

Also, added a frontend test to prove it works:
```
    const input = [
      { name: "zebra" },
      { name: "1" },
      { name: "10" },
      { name: "Apple" },
      { name: "2" },
    ]
    const expected = [
      { name: "1" },
      { name: "2" },
      { name: "10" },
      { name: "Apple" },
      { name: "zebra" }
    ]
```

**Comment by TannerDeLucia** [comment]
hey man, now running on 0.3.4 and Im still seeing the same behavior on my end. Let me know if there's any way i can help.

**Comment by gtsteffaniak** [comment]
@TannerDeLucia hmm, from what I tested I fixed it, can you send a screenshot of what you mean?

**Comment by gtsteffaniak** [comment]
found the issue, the sorting by number was not working because of the extension in the name, I have a fix in v0.3.5 (soon to be released) that sorts without the extension and works:

```
    const input = [
      { name: "zebra.txt" },
      { name: "1.txt" },
      { name: "10.txt" },
      { name: "Apple.txt" },
      { name: "2.txt" },
      { name: "0" }
    ]
    const expected = [
      { name: "0" },
      { name: "1.txt" },
      { name: "2.txt" },
      { name: "10.txt" },
      { name: "Apple.txt" },
      { name: "zebra.txt" }
    ]
```
