### ISSUE TITLE
Remember scroll position after viewing files

### ISSUE THREAD

**Issue by montagdude** [gtsteffaniak/filebrowser#298]
I have a couple folders with many files in them, mostly images and videos. If I scroll down somewhere and double-click a file to view it, when I close the viewer again it says "Loading..." for a second and then brings me back to the top of the list. It is then very tedious to scroll down to the previous position again. I would like file browser to remember the position.

Related (though maybe this belongs in a different issue) can we have scrollbars in desktop view, or at least an option for them?

**Comment by gtsteffaniak** [comment]
A scrollbars is a great idea.

As for the loading and not remembering positions, youre right... looks I changed something on 0.4.0 that stopped it from remembering when you close with the "x" button... 

I'll have that fixed in the next release, for now if you go back with the browser back function it still works as a workaround.

Thanks for opening the issue, this is one of my favorite features and most useful features I've added as well.

**Comment by montagdude** [comment]
Ah, you're right. Using the back button does work. I thought I tried that, but I guess not. Anyway, thanks for the quick response and a great app.

**Comment by gtsteffaniak** [comment]
Thanks, getting issues opened like this are helpful -- this takes 5 seconds to fix and just knowing about it is the hardest part. 

I know why I caused this bug... I was trying to fix an issue with onlyoffice and didn't change it back.

Anyways, if you notice anything else at all that seems like a bug or missing feature, please open new issues like this.

PS: having scrollbar is a great point. I disable the native scrollbar because it messes up with styling, but definitely want to add one. ill add keep that in mind for future versions.

**Comment by montagdude** [comment]
I upgraded to v0.4.1, and this issue remains. Are you sure it made it into the release?

**Comment by gtsteffaniak** [comment]
You mean the yaml parsing error? I did test it and it works on my config file. Just out of curiosity does your yaml file pass a validator like this one:

https://www.yamllint.com/

Edit: oops wrong issue

**Comment by gtsteffaniak** [comment]
Oh sorry was thinking of the other issue , using my phone.

I'll test this issue about the History again, it should be fixed here, will double check

**Comment by gtsteffaniak** [comment]
Yep you're right, I'll have v0.4.2 out today with a fix I tested and confirmed worked... Sorry about that

**Comment by montagdude** [comment]
I don't know, maybe I'm doing something wrong, because the behavior is still the same. Using the back button works, but the close button on the preview always takes me back to the top. I'm running 0.4.2-beta.

**Comment by gtsteffaniak** [comment]
Well figure it out 😅 what browser? Mobile? Ios?

**Comment by montagdude** [comment]
I've tried Chrome and Firefox on Linux, Chrome on Android, and Firefox on iOS.

**Comment by gtsteffaniak** [comment]
Great, I'll test all these next time. Also, this for photos preview, video, editor or what exactly?

**Comment by gtsteffaniak** [comment]
you're not crazy- the v0.4.2 release was actually built with v0.4.1 code! I did a different merge strategy than I normally do, for some reason it produced an old release and called it the new one.

It is definitely fixed in v0.4.2 based on my testing -- give it another shot by doing docker pull / or download v0.4.2 from the [releases](https://github.com/gtsteffaniak/filebrowser/releases/tag/v0.4.2-beta)

**Comment by montagdude** [comment]
Now it works. Thanks!
