### ISSUE TITLE
Drag & drop uploads to the current folder not possible

### ISSUE THREAD

**Issue by athene20** [gtsteffaniak/filebrowser#361]
**Description**
Drag & drop uploads to the current folder not possible

**Expected behaviour**
Upload files by dragging and dropping.

**What is happening instead?**
A local file will open in a new window (file:///...)

**Additional context**
You can upload within a folder by dragging it into the folder.
Same for multiple browsers and Windows/Linux.

**How to reproduce?**
Drag and drop into the Filebrowser file list.

**Files**
Omitted because it is reproducable.

**Comment by gtsteffaniak** [comment]
Thanks for opening this -- I think I know your question:

You can drag uploads to a folder and it will upload to that folder, but trying to drag to the current workspace doesn't work.

I'll have this addressed in the next release.

**Comment by gtsteffaniak** [comment]
tested and fixed in beta v0.5.3

**Comment by Scud0** [comment]
with `(v0.5.3-beta)` i still cannot drag and drop. The browser opens a dragged and dropped file (firefox & MS edge)

**Comment by gtsteffaniak** [comment]
Where exactly are you dropping onto ? Like what part of the UI?

The issue I mentioned above I was able to see the issue: before when. The file was dropped anywhere in the main files view (not sidebar or navbar) it would do exactly what you mentioned.

Was my summary post about accurate?

**Comment by Scud0** [comment]
for me with 053-beta, this is still the case: 

> Thanks for opening this -- I think I know your question:
> 
> You can drag uploads to a folder and it will upload to that folder, but trying to drag to the current workspace doesn't work.
> 
> I'll have this addressed in the next release.

after this :

> tested and fixed in beta v0.5.3

i expected i could drag and drop inside a folder. but that doenst work. Behaviour is still like pre 053-beta

BUT, after some more testing i found the issue:
when the folder i want to drag and drop into is empty (feels lonely here text) it doesnt work. When there are files inside the folder drag and drop does work as expected.

**Comment by gtsteffaniak** [comment]
Ah good catch! so that makes sense. I think it's because the main element is 0 height when empty,

Ok I'll have this fixed soon too!

**Comment by gtsteffaniak** [comment]
closing fixed in v0.5.4, please test and reopen if you still see the issue.

**Comment by Scud0** [comment]
tested; works! 
tnx!
