### ISSUE TITLE
Public share doesn't have the source in the path

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [gtsteffaniak/filebrowser#429]
**Description**
Public share isn't accessible in beta0.6.1.

**How to reproduce?**
- https://github.com/MahmoudAlyuDeen/homelab/tree/main/machines/202-storage
- Define multiple sources.
- Share a folder.
- Open the provided link.

**Expected behaviour**
- Shared folder is displayed.

**What is happening instead?**
- Error: https://storage.alyudeen.mywire.org/share/P51zqRA8K_PZxDp-yKDLHw

**Screenshots**

The source name is missing from the shared path, visible in the URL "storage":
<img width="1281" alt="Image" src="https://github.com/user-attachments/assets/a48e8cc7-8bdb-4684-96c0-af55024293c6" />

👇 

<img width="1189" alt="Image" src="https://github.com/user-attachments/assets/870e708b-ee89-4f71-a5b7-04f58b142def" />

**Comment by gtsteffaniak** [comment]
Ah, I don't have tests for shares yet and I remembered I forgot to test that before releasing.

Sorry about that, more test coverage and a fix to come soon.

**Comment by MahmoudAlyuDeen** [comment]
@gtsteffaniak No worries, I'm happy to help finding and reporting such issues. Your quick confirmation and fixes are awesome!

A bit off-topic: The shared link ignores `userDefaults` defined in the config files: dark mode / display mode / etc... Is this expected or should I maybe open a separate issue for it?

**Comment by gtsteffaniak** [comment]
I think the public user just needs to be kept up-to-date on startup, applying the "current" userDefaults. definitely a good idea to add.

**Comment by MahmoudAlyuDeen** [comment]
No pressure or anything, I just wanted to let you know that your repo (including this issue 😅 for now), is being featured in my `readme` here: https://github.com/MahmoudAlyuDeen/diwansync.

Your design gets attention when sharing [on reddit too](https://www.reddit.com/r/minilab/comments/1jdt1qq/comment/miez4aw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), great work!

**Comment by gtsteffaniak** [comment]
Awesome I appreciate that! it won't be too much longer before a stable release is ready and then I will advertise it a bit more.

FYI closing since this should be fixed in v0.6.2

**Comment by MahmoudAlyuDeen** [comment]
The issue is not resolved, even though the path is now correct when sharing, accessing the link results in a `500` response:

<img width="1805" alt="Image" src="https://github.com/user-attachments/assets/574623d6-078d-432a-9499-600f2cb6d9e9" />

**Comment by gtsteffaniak** [comment]
Hmm ok I'll take another look.

Share links don't need the source, it's part of the hash info. The source info is designed to be hidden from share links for the purpose of security. A share link is abstracted from the source info and keeps the source private from the user.

(Eventually a share link could be a collection of files from more than one source)

But getting a 500 error does indicate an issue. Perhaps I broke compatibility with existing shares, can you try creating a new share and see if the issue persists?

I'll add backwards compatibility in a bugfix pr

**Comment by MahmoudAlyuDeen** [comment]
The screenshot is from a newly created share link. created on v0.6.2: https://storage.alyudeen.mywire.org/share/76klfcgwHfJf6-rQjVdwwA

**Comment by gtsteffaniak** [comment]
Can you provide a few details so I can try to replicate?

- your config (omit any sensitive info) 
- what platform (windows? docker? using binary?)
- the "response message" from the server for the 500 request. You gave a screenshot that showed it in the dev-tools , but there should be a message on the "response" tab about why it gave a 500.

**Comment by gtsteffaniak** [comment]
now that I look at the config you provided, I haven't tested with [noauth ](https://github.com/MahmoudAlyuDeen/diwansync/blob/e4b2481c066a8fb25b4ca3355989683ad457dde6/machines/202-storage/config.yaml#L9C1-L10C1)-- perhaps that's the issue. Let me give it a try.

**Comment by gtsteffaniak** [comment]
fix is in v0.6.3

**Comment by MahmoudAlyuDeen** [comment]
Fix [confirmed in v0.6.3](https://storage.alyudeen.mywire.org/share/emEI0EvdFzyrw7YrToSohw) 🎉 Thanks for the quick support.

**Comment by MahmoudAlyuDeen** [comment]
> A bit off-topic: The shared link ignores `userDefaults` defined in the config files: dark mode / display mode / etc... Is this expected or should I maybe open a separate issue for it?

Should I file a separate issue for this? 🤔

**Comment by gtsteffaniak** [comment]
Yes I didn't add that , please do so I can tag it for competition

**Comment by MahmoudAlyuDeen** [comment]
Done: https://github.com/gtsteffaniak/filebrowser/issues/451. What competition? 🤔

**Comment by gtsteffaniak** [comment]
Oops autocorrect typo, I meant "for completion".  I'm messaging from my phone :)
