### ISSUE TITLE
`<username>` folder added when manually changing scope (Only for `createUserDir: true`)

### ISSUE THREAD

**Issue by BaccanoMob** [gtsteffaniak/filebrowser#541]
**Description**
To correct the behavior #537 I thought I could change the scope after the user is created.

**Expected behaviour**

Creating a new user `test`

![Image](https://github.com/user-attachments/assets/58b449f1-c77f-4329-b7c8-4f912a0b5025)

Updating scope from `/test` to `/home/test` should create a folder for that said path.

**What is happening instead?**

Instead of creating `/home/test`, it creates `/home/test/test` (aka it creates a new `/test` user dir for new base scope programmatically I think). 

![Image](https://github.com/user-attachments/assets/2b9a4728-a850-44d9-b154-29185c01ca46)

From `test` user's login, (it just creates user directory in that scope when updating, so the scope is still `/home/test`  for that user)

![Image](https://github.com/user-attachments/assets/daed0fe5-e7f5-4966-8d56-d102159d2495)

**Additional context**

If `/test` has contents, it does not move over to the new scope. Thankfully `/test` does not get deleted though you still need an admin user to move the folder.

Maybe `createUserDir: true` should be applicable only when creating users but not when updating users.

**Comment by gtsteffaniak** [comment]
You can change scope at any time, but the `createUserDir` feature is only a one time feature at user creation.

Right now scope changes requires the path to exist. I could add validation and warnings for paths that don't exist, as well as a feature to create a new path scope if it doesn't exist.

All of that would need UI warnings and some override flag. I wouldn't want typos to cause random directories to get created (although that would happen on user create)... 

Do I understand the issue correctly? Changing the scope after the user is updated should behave the same as when the user is was first created?

**Comment by BaccanoMob** [comment]
> Do I understand the issue correctly? 

Unfortunately, you don't. I am also saying `You can change scope at any time, but the createUserDir feature is only a one time feature at user creation`. Are you sure `createUserDir` works only when user is created?

> Right now scope changes requires the path to exist. I could add validation and warnings for paths that don't exist, as well as a feature to create a new path scope if it doesn't exist.

That would be good feature to add. Though I think `scope changes requires the path to exist` is not fully enforced (with v0.6.8 atleast) without any validation. (check below steps for why)

---

**Steps to reproduce**

1. Update config's sources to below
```yaml
    - path: "/data"
      name: data
      config:
        defaultUserScope: "/home"
        defaultEnabled: true
        createUserDir: true
    - path: "/abc"
      name: abc
    - path: "."
      name: backend
```

2. Login with admin user and create user with access to all above (Note: do not type anything in scopes, just add all sources to the user). you will get below in User Management (only `data` gets `/newtest` not `/home/newtest` prolly due to #537 even though `/home` is specified as default user scope)

![Image](https://github.com/user-attachments/assets/48f3a905-c0ff-4c6b-b975-6682afb167dc)

3. You can check that `/newtest` is actually created.
4. Now, change the scope for `newtest` user's from `/newtest` to `/home/newtest` (as if you are correcting it).

![Image](https://github.com/user-attachments/assets/18d2bec7-407a-4228-9927-39b20de7839b)

5. But instead of  creating `/home/newtest` it creates ``/home/newtest/newtest`. (This is what I mentioned in the issue)
6. Now, update other 2 scopes with `/newtest` (or any multi folder path).

![Image](https://github.com/user-attachments/assets/6ed7635a-d5de-458a-8c28-adaebed6c7fd)

7. But no folder is created in this case (meaning scopes at the moment do not require the path to exist on save). If I login into `newtest` I get

`Error: {"status":500,"message":"could not stat path: /abc/newtest, lstat /abc/newtest: no such file or directory"}`

![Image](https://github.com/user-attachments/assets/f72d2473-9a01-421e-96aa-e8e32e748bf5)

8. Now back to admin user so I can update scopes. I update path to non defaultUserScope for defaultUserScope enabled source like `/path/to/something`

![Image](https://github.com/user-attachments/assets/91d7079d-de3a-412d-9bc2-b1ea0403d075)

9. Instead of  `/path/to/something` created, I get  `/path/to/something/newtest` created. 

Note: if the scope is `/` only then, `/<username>` gets created. This is prolly why `admin` is there in start up (screenshot in [this comment](https://github.com/gtsteffaniak/filebrowser/issues/537#issuecomment-2807215470) at the end).

At this point I assumed you do not create directories unless `createUserDir: true` which adds a user directory (hence the title). If you did plan to create directories when mentioned a scope, I would go with you suggestion of introducing validation/warnings which I mentioned above its a good feature to add. At the moment, I had manually add the folders unless  `createUserDir: true` which creates automatically.

And for some reason it appends `<username>` folder to the scope when `createUserDir: true` (which is the bug I noticed and raised this issue). Its as if it adds user directory to the scope even though I manually specified a scope (that is, it makes as if the createUserDir feature is **not** an one time feature and it creates when user directories when createUserDir is enabled regardless of time). 

Hope I gave a good clarity about this issue. (also I believe it is partly coupled with #537, so you might have to review the whole scope logic at some point).

**Comment by gtsteffaniak** [comment]
0.7.1 has changes to this. I believe it should work as intended, can you confirm?

**Comment by BaccanoMob** [comment]
> And for some reason it appends <username> folder to the scope when createUserDir: true (which is the bug I noticed and raised this issue). Its as if it adds user directory to the scope even though I manually specified a scope.

Unfortunately, I think `createUserDir` still influences when setting a scope. For example, manually changing to `/path` creates `/path/<username>` (path validator makes sure `/path` exists). 

Note that, this also makes it impossible have `/` scope for that source now since admin accounts also enforces user directory as scope. 

Maybe you need a Bool to check if setting a scope is for a new user or updating a user? where the Bool is true when creating a user and false when updating one...

My recommendation is remove `createUserDir` feature temporarily. Implement #434 so you set list of scopes. Once done, you can  reimplement `createUserDir` again. But this time make frontend auto add user directory via a check box `create user directory` if createUserDir: true and also can be disabled (and this should be accessible only for admins).  If checked it creates user directory and appends to the list of scopes. That way list of scopes for sources is as is you see on screen.

Or make sure you fix this before #434 or you have <username> folders for every scope in that list.

**Comment by gtsteffaniak** [comment]
I believe this is fixed in v0.7.2 -- only an admin can set user scopes and whatever is specified is exactly set when modified.

**Comment by BaccanoMob** [comment]
Yea, it is fixed. But... the default user scope with createUserDir as true should default to user dir.

Steps to reproduce:
1. Create a user => `[ { "name": "data", "scope": "/home/asdfg" } ]` where data has default user scope `/home` and createUserDir as true. 🆗 
2. Change to `/` now works!! => `[ { "name": "data", "scope": "/" } ]` 🆗 
3. Remove scope `/` to let the default value take place => `[ { "name": "data", "scope": "/home" } ]` aka just the default user scope excluding user dir. That user will get access to all user dir now. So the scope should add `<username>` to the default user scope here.

**Comment by gtsteffaniak** [comment]
Hmm yeah that last condition, is still not exactly what we want, thanks for pointing that out.

The goal was to have user creation behave one way, then user save behave another.

I'll add that to the list of changes.
