### ISSUE TITLE
File editor overwrites content of file with previously edited file.

### ISSUE THREAD

**Issue by petihu** [gtsteffaniak/filebrowser#701]
**Description**
If I edit multiple files one after each other, after about 10 edits, the editor starts to write the contents of the previously edited file to the current one, overwriting its contents.
I use the docker image with ffmpeg, (v0.7.6-beta) in a chromium browser. Container runs as root.

**Expected behaviour**
Save the newly added contents to the file.

**What is happening instead?**
The contents of the previously edited file overwrites the current one, losing all the new data instead of saving it.

**Additional context**
Sometimes, the lost data somehow comes back if I edit another file and save it (overwriting it and losing that files contents too)

**How to reproduce?**
Create multiple files in a folder (for example test1.txt, test2.md, test3.yaml), and modify them one after the other multiple times. I ran into the issue approx after 10-15 edits.

**Files**
Example: After editing the test.txt file, I tried to edit test2.md and after saving, it got overwritten with contents of test.txt Initially every file content was different.
![Image](https://github.com/user-attachments/assets/55c3f9a2-7102-41bb-b5e3-382f55cc1057)

![Image](https://github.com/user-attachments/assets/3543a2bb-3a4c-44d5-8689-030d6902d17a)

![Image](https://github.com/user-attachments/assets/437e56c0-0f2c-4344-a39b-8ee8a19f6ab9)

**Comment by gtsteffaniak** [comment]
Very interesting it takes so many attempts. Let me try to reproduce and see what's going on.

**Comment by xX-MrN0b0dy-Xx** [comment]
I noticed that too, even just creating and editing a temporary `.txt` file inside the container multiple times.

I am utilizing the `0.7.6-beta` image.

I noticed that as long as the file is small, if you don't save the edits too frequently, lets's say not under 3s, everything seems fine even after 3-4 edits.

But if u paste for instance a [generated Lorem Ipsum Dolor example](https://www.lipsum.com/) of 10Mb, even just a second modification 40-45s after the first saving with the pasted text, breaks the file (ofc permissions has been checked and everything is fine).

Moreover, creating a new `.txt` file with different name and some small random text inside, will randomly show some of the text from the former edited file.

I am neither a developer, nor I know Go, bit it seems some sort of frontend cache handling problem or a race condition/save lag problem in the backend? Idk...

**Comment by gtsteffaniak** [comment]
don't worry I will fix, plan to release tomorrow.

**Comment by gtsteffaniak** [comment]
I believe this is fixed, but I will need you to confirm because I could not replicate this myself. But I made changes which could help with the caching. Could you all confirm? try out 0.7.7-beta

**Comment by xX-MrN0b0dy-Xx** [comment]
> I believe this is fixed, but I will need you to confirm because I could not replicate this myself. But I made changes which could help with the caching. Could you all confirm? try out 0.7.7-beta

Unfortunately it's still present using `0.7.7-beta`. It seems to behave better, namely if I try to edit small files the bug doesn't occur. But when u edit slightly bigger files, it occur.

To replicate:
- Create a .txt file named as u wish and a secondary .txt with another name
- Paste some random typed chars in both and save both
- Generate a 900Kb or sth Lorem Ipsum text [using ie this link](https://www.lipsum.com/) and paste it into one of the two .txt and save
- Now, as quick as possible open the other .txt, type something and save. Then open the bigger .txt and delete a line, save and close. Open the first smaller .txt and close it (if u want, u can even slightly edit it again. Now re-open the bigger file and probably everything is lost, the file is either broken or it contains just one of the edited versions of the other file

I know this is probably kinda of an edge case, but given that both the .txt are less than 500Kb, I'm scared that with bigger files (almost anything is bigger), there could be problems ie just editing a 1Mb file and then open another one. I mean... idk, I don't know what's causing this problem so idk what could be the impact and even if the dimension itself is a problem or not.

Just out of curiosity, I tried also [filebrowser-og latest](https://github.com/filebrowser/filebrowser/releases/tag/v2.32.0) on a virgin setup, exactly with the same text, same bind mount, same everything as I did for quantum and the problem didn't showed up, so it's something with this fork.

**Comment by wassereimer86** [comment]
As I've written in #738 , I had this 6 times in two days. For me, it's not an edge case. I'm just rapidly changing things in files and in my case, most of the files were small (from one with 4 short lines up to one with 70 short lines) when it happened.

How I was able to reproduce it: I created two files in a directory. a.yaml and b.log (I also had this bug with two yaml files). In a.yaml is the content from my screenshot in my post and in the b.log is part of an access.log file. Not very small but not big (1152 rows). I opened file a, closed it, opened file b, closed it, opened file a and instantly hit save. Now I have the content of file b in file a like in the screenshot of my post. I also had this while i really changes something in a file and saved after that.

**Comment by gtsteffaniak** [comment]
Ah that's another good clue. This happensare multiple open tabs/windows?

Could be a shared state between tabs.

**Comment by xX-MrN0b0dy-Xx** [comment]
> Ah that's another good clue. This happensare multiple open tabs/windows?
> 
> Could be a shared state between tabs.

At least in my case, I did evth from the same tab so I don't think it is due to that.

**Comment by wassereimer86** [comment]
> Ah that's another good clue. This happensare multiple open tabs/windows?
> 
> Could be a shared state between tabs.

I have another Tab from the other Instance open, but per instance only one tab ion which i work and switch between files. So I also doubt that there is a problem with multiple tabs/windows/instances.

**Comment by gtsteffaniak** [comment]
I still couldn't reproduce, but I think I know what the issue might be. I added more protections against this issue in [0.7.8-dev](https://hub.docker.com/layers/gtstef/filebrowser/0.7.8-dev/images/sha256-098afa490692d691421ce669f01ec3c67ad39e8eae57a2bc8f4c5b2710e8e720)

If someone is using docker, could they test out this dev image and see if it still has the issue?

**Comment by gtsteffaniak** [comment]
released the change with 0.7.8, please test and let me know.

**Comment by petihu** [comment]
Hi!
I tried v0.7.8, it seems that the problem is gone, i could not reproduce it with this version.

btw thank you for your work, this software is very promising.

**Comment by wassereimer86** [comment]
I tried really hard, but was also not able to reproduce the problem with the latest version. 🙂 Thank you!

**Comment by gtsteffaniak** [comment]
That's great to hear, sounds like that was the issue. It should now be basically impossible to save incorrect data, it will error if the data tries to go to the wrong file.

I put a safeguard on load and a safeguard on save action.

Thanks for confirming I'll consider this closed.

**Comment by xX-MrN0b0dy-Xx** [comment]
I stress tested it over any normal use case and I can confirm that now behaves as expected with `0.7.8-beta`. Also, I love the previews of the text files. What a wonderful thing u're creating!
