### ISSUE TITLE
`[WARN ] user admin is not allowed to login with oidc authentication, bypassing and updating login method`

### ISSUE THREAD

**Issue by poperigby** [gtsteffaniak/filebrowser#811]
I have an `admin` user defined by my authentication provider (Authelia) that is part of the `lldap_admin` group. When I try to login via this user, I get this warning:

```
[WARN ] user admin is not allowed to login with oidc authentication, bypassing and updating login method
```

Then the `admin` user ends up not actually being an administrator.

Here's my configuration:

```yaml
server:
  port: 8282
  sources:
    - path: "/mnt/media/files"
      config:
        createUserDir: true
auth:
    methods:
        password:
            enabled: false
        oidc:
            enabled: true
            clientId: xxx
            clientSecret: xxx
            issuerUrl: "https://auth.haddock.cc"    # authorization URL of the OIDC provider
            scopes: "email openid profile"          # scopes to request from the OIDC provider
            userIdentifier: "username"              # the user identifier to use for authentication. Default is "username", can be "email" or "username", or "phone"
            createUser: true                        # create user if it does not exist
            adminGroup: "lldap_admin"               # users in this group will be granted admin privileges.
```

**Comment by gtsteffaniak** [comment]
Thanks for opening an issue on this, I recognize many users are choosing oidc or proxy only authentication, disabling password.

Filebrowser quantum always creates a default adminlogin user  on the backend, but I think I need to change this.

**Comment by poperigby** [comment]
I updated to v0.7.10 and it's still giving me the same warning and not making the user an actual administrator. I changed `userIdentifier` to `preferred_username`.

**Comment by poperigby** [comment]
Do I have to somehow delete the admin user first? If so, it would be great to have an option to not create it at all.

**Comment by gtsteffaniak** [comment]
No you don't need to delete the user.

Do you ever login with that user via password instead of oidc?

I bet I know whats happening, you probably are not mounting a persistent database properly. With OIDC its hard to tell if you don't have a persistent database, do you see "using existing database" in start up logs?

[Several others have made that mistake](https://github.com/gtsteffaniak/filebrowser/issues/814)

**Comment by poperigby** [comment]
> Do you ever login with that user via password instead of oidc?

No, I've never logged in with a password.

> I bet I know whats happening, you probably are not mounting a persistent database properly. With OIDC its hard to tell if you don't have a persistent database, do you see "using existing database" in start up logs?

It's saying this in the log at startup, so I don't think that's the case?

```
Using existing database  : database.db
```

**Comment by gtsteffaniak** [comment]
0.7.11 should fix this, since you have password auth disabled, just make sure to unset any adminPassword in your config/environment and it will not get reset anymore.

**Comment by poperigby** [comment]
I updated and it's still happening 😢. Here's the log from a fresh install and logging in with Authelia with my `admin` user:

```
[INFO] Using OIDC Client ID from FILEBROWSER_OIDC_CLIENT_ID environment variable
[INFO] Using OIDC Client Secret from FILEBROWSER_OIDC_CLIENT_SECRET environment variable
[INFO ] OIDC Auth configured successfully
[INFO ] Initializing FileBrowser Quantum (untracked)
[INFO ] Using Config file        : /nix/store/wk49ib0c2jr4v1raln56k8xyi0ngjhnp-config.yaml
[INFO ] Auth Methods             : [oidc]
[INFO ] Creating new database    : database.db
[INFO ] Sources                  : [files: /mnt/media/files]
[INFO ] Resetting admin user to default username and password.
[INFO ] MuPDF Enabled            : false
[INFO ] Running at               : http://localhost:8282/
[INFO ] initializing index: [files]
[INFO ] Index assessment         : [files] complexity=simple directories=523 files=1672
GET     | 200 | 127.0.0.1:33866 | N/A          | 0ms          | "/"
GET     | 401 | 127.0.0.1:33872 | N/A          | 0ms          | "/api/users?id=self"
GET     | 302 | 127.0.0.1:33872 | N/A          | 2ms          | "/api/auth/oidc/login?redirect=%2Ffiles%2F"
[WARN ] user admin is not allowed to login with oidc authentication, bypassing and updating login method
GET     | 302 | 127.0.0.1:33872 | admin        | 355ms        | "/api/auth/oidc/callback?code=authelia_ac_WM-Vse-JzvqQY8tG9wSspa67oF2pcdcHZATzleGzjy4.gxB8zNZ7hHPGK_toMEORaPZ-LIQlPu8FGWFYN9JSHrs&iss=https%3A%2F%2Fauth>
GET     | 200 | 127.0.0.1:33872 | N/A          | 0ms          | "/files/"
GET     | 200 | 127.0.0.1:59566 | admin        | 0ms          | "/api/users?id=self"
GET     | 200 | 127.0.0.1:59566 | admin        | 0ms          | "/api/resources?path=%2F&source=files"
GET     | 200 | 127.0.0.1:59566 | admin        | 0ms          | "/api/jobs/status/sources"
GET     | 200 | 127.0.0.1:59566 | admin        | 0ms          | "/api/users"
GET     | 200 | 127.0.0.1:59572 | admin        | 0ms          | "/api/auth/tokens"
GET     | 200 | 127.0.0.1:59582 | admin        | 0ms          | "/api/shares"
```

**Comment by gtsteffaniak** [comment]
`Initializing FileBrowser Quantum (untracked)` seems to not be a tagged version?

also you can see ` Resetting admin user to default username and password.` , this means you provided `adminPassword` in your config to reset.

**Comment by poperigby** [comment]
I'm definitely building from 0.7.11-beta, I just wasn't setting the version string correctly when I was building the Go package. It should be fixed now. 

Here's the output of `filebrowser version`:

```
FileBrowser Quantum - A modern web-based file manager
        Version          : v0.7.11-beta
        Commit           : 7619840a8109196eba5aed5f504bb75c98b7ea63
        Release Info     : https://github.com/gtsteffaniak/filebrowser/releases/tag/v0.7.11-beta
```

Here's a first run log:

```
[INFO] Using OIDC Client ID from FILEBROWSER_OIDC_CLIENT_ID environment variable
[INFO] Using OIDC Client Secret from FILEBROWSER_OIDC_CLIENT_SECRET environment variable
[INFO ] OIDC Auth configured successfully
[INFO ] Initializing FileBrowser Quantum (v0.7.11-beta)
[INFO ] Using Config file        : /nix/store/wk49ib0c2jr4v1raln56k8xyi0ngjhnp-config.yaml
[INFO ] Auth Methods             : [oidc]
[INFO ] Creating new database    : database.db
[INFO ] Sources                  : [files: /mnt/media/files]
[INFO ] Resetting admin user to default username and password.
[INFO ] MuPDF Enabled            : false
[INFO ] Running at               : http://localhost:8282/
[INFO ] initializing index: [files]
[INFO ] Index assessment         : [files] complexity=simple directories=523 files=1672
GET     | 200 | 127.0.0.1:51548 | N/A          | 1ms          | "/"
GET     | 401 | 127.0.0.1:51562 | N/A          | 0ms          | "/api/users?id=self"
GET     | 302 | 127.0.0.1:51562 | N/A          | 0ms          | "/api/auth/oidc/login?redirect=%2Ffiles%2F"
[WARN ] user admin is not allowed to login with oidc authentication, bypassing and updating login method
GET     | 302 | 127.0.0.1:51562 | admin        | 370ms        | "/api/auth/oidc/callback?code=authelia_ac_7MbZskz48SSmA5lcVAn0c5m46Y5uy2aPNZ2tzQXgaNk.X21QT1Vpb-ZoVMxYViUpK7GxgqM9gSJqjS257b2x1Uw&iss=https%3A%2F%2Fauth.haddock.cc&scope=email+openid+profile&state=1qt2xn7xyz57us2x%3A%2Ffiles%2F"
GET     | 200 | 127.0.0.1:51562 | N/A          | 0ms          | "/files/"
GET     | 200 | 127.0.0.1:51568 | admin        | 0ms          | "/api/users?id=self"
GET     | 200 | 127.0.0.1:51568 | admin        | 0ms          | "/api/resources?path=%2F&source=files"
GET     | 200 | 127.0.0.1:51568 | admin        | 0ms          | "/api/jobs/status/sources"
GET     | 200 | 127.0.0.1:51568 | admin        | 0ms          | "/api/shares"
GET     | 200 | 127.0.0.1:51578 | admin        | 0ms          | "/api/users"
GET     | 200 | 127.0.0.1:51580 | admin        | 0ms          | "/api/auth/tokens"
```

This is my configuration file:

```yaml
auth:
  methods:
    oidc:
      adminGroup: lldap_admin
      createUser: true
      enabled: true
      issuerUrl: https://auth.haddock.cc
      scopes: email openid profile
    password:
      enabled: false
server:
  port: 8282
  sources:
  - config:
      createUserDir: true
    path: /mnt/media/files
```

**Comment by gtsteffaniak** [comment]
I see the issue, I mentioned it earlier in the [above comment](https://github.com/gtsteffaniak/filebrowser/issues/811#issuecomment-3001270657)

Your admin user is getting reset on database creation because you don't have a persistent set:

```
[INFO ] Creating new database    : database.db
```

Also, since your admin username matches the one used by OIDC, there's a conflict. So I would recommend:

1. Set your default admin username to something unique via `auth.adminUsername: local_admin` (this alone will fix the issue technically)
2. I'd also recommend configuring your database to be persistent. see [getting started wiki for examples](https://github.com/gtsteffaniak/filebrowser/wiki/Getting-Started#docker-compose)
