### ISSUE TITLE
Issues with the WebUI

### ISSUE THREAD

**Issue by Kurami32** [gtsteffaniak/filebrowser#989]
**Description**
I found some issues in the Web UI, I think that I should post them (I want to help).

- Incorrect number of files on sources.
- Some folders (and sub-folders inside) display no size (0.00B) when you change the name of them.
- When I edit some file, I need to wait until the thumbnail is updated.
- The URL bar haves a different path that where you are currently? (this persist even reloading the page).
- When I upload some file, this not appear (show) until I refresh the page.
- When I log in (or any user log in), all is empty until I click on some sources.

**Expected behavior**
All the described above should work fine, without these issues.

**Additional context**
Here is a video that I recorded with the issues mentioned, sorry for my crap editing or if is not very clear. (Is my first time editing a video on Kdenlive lol).

https://github.com/user-attachments/assets/7590da64-9fef-4c25-ba42-a60229a7c469

**Comment by gtsteffaniak** [comment]
thanks for opening an issue for these and including the detailed video this is great.. There are some good explanations for your issues and some that are bugs:

1. Incorrect number of files on sources
    - This is a bug, I see on the backend some files can get counted on each refresh multiple times in some cases.
2. Some folders (and sub-folders inside) display no size (0.00B) when you change the name of them.
    - There't two parts to this issue. FIrst, renaming folders will require a refresh of the index to update the values fully. This is something not too easy to do efficiently (copy the index tree to a new parent name) and I am looking at how to do it efficiently. Second, the rename operation doesn't trigger a refresh like to should automatically (it shouldn't wait for indexing) . That is a bug.
3. When I edit some file, I need to wait until the thumbnail is updated.
    - The preview doesn't refresh unless the mod time changes, but this should be happening immediately, let me check the cause for this.
4. The URL bar haves a different path that where you are currently? (this persist even reloading the page).
    - All paths will be prefixed by `files` this is expected and not an issue. What you are highlighting is the hash which can be used to track the last file accessed for scrolling memory. Not a bug from what I see.
5. When I upload some file, this not appear (show) until I refresh the page.
    - This is something that changed with the new upload prompt recently added. I plan to address this by refreshing each time the upload state goes from "uploading" to "finished", that way it only refreshes after everything is uploaded completely once.
6. When I log in (or any user log in), all is empty until I click on some sources.
    - This used to work via a "redirect to first source if none is specified" mechanism that I think stopped working in the past few version changes, this is likely a bug.

**Comment by gtsteffaniak** [comment]
- [needs confirming] Incorrect number of files on sources.
- ✅ [fixed in 0.7.16] Some folders (and sub-folders inside) display no size (0.00B) when you change the name of them.
- [needs confirming, worked when I tested] When I edit some file, I need to wait until the thumbnail is updated.
- ✅ [fixed in 0.7.16] The URL bar haves a different path that where you are currently? (this persist even reloading the page).
- ✅ [fixed in 0.7.16] When I upload some file, this not appear (show) until I refresh the page.
- ✅ [fixed in 0.7.16] When I log in (or any user log in), all is empty until I click on some sources.

**Comment by Kurami32** [comment]
Thanks! That was fast haha. I've been testing a bit, and this is my summary:
 
1. Nope, is still showing incorrect numbers on my source (shared) where I have only one video:
<img width="931" height="653" alt="Image" src="https://github.com/user-attachments/assets/7ef9394a-0210-41f2-b3cd-bfdca05fe849" />

This is my other source (Files), I don't have that amount of files:
<img width="341" height="231" alt="Image" src="https://github.com/user-attachments/assets/976c8307-6359-4260-a072-f4b9aff59d04" />

2. This is partially fixed. If I add numbers or special characters on the name (like " _ ? @ ! ' or brackets) the folder (and sub-folders) shows 0.0 bytes, but if I rename it again without numbers and only letters, the folder shows its size.

3. Is still occurring, takes a while for the thumbnail to update.
4. Is still there, but you mentioned before that's not a bug. Sometimes I need to do 2-3 clicks (with the side keys of the mouse) for return to the previous page/folder.
5. This is fixed! Now I upload a file, and shows immediately, the thumbnail shows too.
6. This seems fixed too!

I'll continue testing and see if I find another related bug.

**Comment by gtsteffaniak** [comment]
newly fixed:
✅ [fixed in 0.7.18] Incorrect number of files on sources.
✅ [fixed in 0.7.18] When I upload some file, this not appear (show) until I refresh the page.

**Comment by gtsteffaniak** [comment]
only remaining issue is 


2. Some folders (and sub-folders inside) display no size (0.00B) when you change the name of them.
> There't two parts to this issue. FIrst, renaming folders will require a refresh of the index to update the values fully. This is something not too easy to do efficiently (copy the index tree to a new parent name) and I am looking at how to do it efficiently. Second, the rename operation doesn't trigger a refresh like to should automatically (it shouldn't wait for indexing) . That is a bug.

This is partially fixed. If I add numbers or special characters on the name (like " _ ? @ ! ' or brackets) the folder (and sub-folders) shows 0.0 bytes, but if I rename it again without numbers and only letters, the folder shows its size.

**Comment by Kurami32** [comment]
Thanks!
About the number of files/folders, the issue still there. At the start, the sources show the real amount of files/folders, but if I start to navigate a bit the number goes wrong again.

**Comment by gtsteffaniak** [comment]
I am not sure -- it doesn't do this for me and I did find a root cause that resolved this. Are you still seeing this issue?

**Comment by Kurami32** [comment]
> I am not sure -- it doesn't do this for me and I did find a root cause that resolved this. Are you still seeing this issue?

Seems that not, my sources are showing their amounts of files.

**Comment by Kurami32** [comment]
And about this...
> This is partially fixed. If I add numbers or special characters on the name (like " _ ? @ ! ' or brackets) the folder (and sub-folders) shows 0.0 bytes, but if I rename it again without numbers and only letters, the folder shows its size.

I'm having issues with that (also, now I can't name/rename a file/folder with a underscore (_) or At (@) If I try give me an error). But I think that is better open a new issue and reference this one.

**Comment by gtsteffaniak** [comment]
please do open a new issue for `now I can't name/rename a file/folder with a underscore (_) or At (@) If I try give me an error`

I just tested again and seems to work for me but a fresh issue request with details could help.

For now I am closing this one!

**Comment by Kurami32** [comment]
> please do open a new issue for `now I can't name/rename a file/folder with a underscore (_) or At (@) If I try give me an error`
> 
> I just tested again and seems to work for me but a fresh issue request with details could help.
> 
> For now I am closing this one!

Thanks! And I forget to mention, I can name/rename with At (@) and underscores (_), that is fine. 

I opened another related issue with the slashes now.
